"""Agent-specific example inputs for the Try It tab.

Each entry: (keywords, placeholder, label, [list of 10+ examples])
The function returns (placeholder, label, examples_list) based on agent name keywords.
"""

HINTS = [
    (["receipt", "expense", "invoice", "spend", "categorize", "receipt-categorizer"], "Paste receipt text or describe expense...", "🧾 Receipt / Expense", [
        "Walmart $45.20 for groceries on Oct 12",
        "Uber ride to airport $35.00",
        "Coffee at Starbucks $4.50",
        "Bought a new laptop for $1200 at BestBuy",
        "Dinner with client at Joe's Steakhouse, $150.00",
        "Flight to NY via Delta, $380, Nov 15",
        "Monthly Notion subscription $10",
        "Target $89.99 for office supplies",
        "Gas station fill up $42.50 Shell",
        "Hotel stay Marriott $450 for 2 nights",
    ]),
    (["draft", "compose", "write email", "reply", "email-draft"], "Enter bullet points to draft an email...", "✍️ Draft Email", [
        "draft an email to the team: we hit our Q3 goals, great job everyone, taking Friday off",
        "write an email to client: project is delayed by 1 week, apologies, new deadline is next Friday",
        "reply to recruiter: interested in the role, available for a call tomorrow at 10am",
        "email to manager: requesting 2 weeks PTO in August for family vacation",
        "draft intro for new hire: meet Sarah, joining as Senior Designer, previously at TechCorp",
        "send reminder to marketing: need the final slide deck by 3pm today for the all-hands",
        "decline vendor proposal: thanks for the time, went with another solution, stay in touch",
        "follow up after interview: great meeting the team, excited about the roadmap, attached references",
        "announce to company: new health benefits plan starting next month, FAQ attached",
        "apologize for missing meeting: stuck in traffic, please share recording and notes",
    ]),
    (["email", "triage", "inbox", "newsletter"], "Paste email text here...", "📧 Paste Email", [
        "Subject: Q3 Budget Review Meeting\n\nHi Team,\n\nPlease review the attached Q3 budget proposal before Friday. We need to finalize the marketing spend.\n\nThanks,\nSarah",
        "Subject: URGENT: Server Down in Production\n\nThe main API server is returning 503 errors since 2:15 AM. Customer complaints are flooding in. Need someone from DevOps to investigate ASAP.\n\n- Error rate: 89%\n- Affected: US-East region\n- Last deploy: yesterday 6 PM",
        "Subject: Re: Partnership Proposal from TechCorp\n\nHi Mark,\n\nThanks for forwarding. The terms look reasonable but I have concerns about the exclusivity clause in Section 4. Can legal review before we respond?\n\nBest,\nLisa",
        "Subject: Your Weekly Newsletter - Top 5 AI Tools\n\n1. Claude - Best for coding\n2. ChatGPT - Best for general use\n3. Midjourney - Best for images\n4. Cursor - Best IDE\n5. Perplexity - Best for research\n\nSubscribe for more!",
        "Subject: Invoice #4521 - Payment Overdue\n\nDear Client,\n\nThis is a reminder that Invoice #4521 for $3,450 was due on Jan 15. Please process payment at your earliest convenience to avoid late fees.\n\nRegards,\nAccounting",
        "Subject: Team Offsite Planning - March 2025\n\nHi everyone,\n\nI'm organizing our Q1 team offsite. Please vote on your preferred dates:\nA) March 10-12\nB) March 17-19\nC) March 24-26\n\nLocation: TBD (suggestions welcome!)",
        "Subject: Security Alert: Unusual Login Detected\n\nWe detected a login from an unrecognized device in São Paulo, Brazil at 3:42 AM EST. If this wasn't you, please reset your password immediately.",
        "Subject: Feedback on Product Roadmap v2\n\nHi Product Team,\n\nI reviewed the roadmap. A few thoughts:\n- Love the AI integration timeline\n- Concerned about Q3 scope creep\n- Can we prioritize mobile app over desktop?\n\nLet's discuss Thursday.",
        "Subject: Job Application - Senior Engineer\n\nHi Hiring Manager,\n\nI'm applying for the Senior Engineer position. I have 7 years of experience in distributed systems and currently lead a team of 5.\n\nResume attached.\nBest, Alex",
        "Subject: Shipping Confirmation - Order #78234\n\nYour order has shipped! Tracking: 1Z999AA10123456784\nEstimated delivery: Feb 28\n\nItems:\n- Mechanical Keyboard x1\n- USB-C Hub x1\n- Monitor Stand x1",
        "Subject: Can we reschedule tomorrow's standup?\n\nHey team, I have a dentist appointment at 9 AM. Can we move standup to 10:30? Or I can join async via Slack.",
    ]),
    (["sql", "database", "query", "schema", "migration"], "Paste SQL or describe your query...", "🗄️ SQL / Query", [
        "SELECT u.name, COUNT(o.id) as order_count, SUM(o.total) as revenue\nFROM users u\nLEFT JOIN orders o ON u.id = o.user_id\nWHERE o.created_at > '2024-01-01'\nGROUP BY u.name\nHAVING COUNT(o.id) > 5\nORDER BY revenue DESC\nLIMIT 20;",
        "CREATE TABLE products (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(255) NOT NULL,\n  price DECIMAL(10,2),\n  category_id INT REFERENCES categories(id),\n  created_at TIMESTAMP DEFAULT NOW()\n);",
        "UPDATE orders SET status = 'shipped', shipped_at = NOW()\nWHERE status = 'processing'\nAND payment_verified = true\nAND created_at < NOW() - INTERVAL '2 days';",
        "SELECT DATE_TRUNC('month', created_at) as month,\n  COUNT(*) as signups,\n  COUNT(*) FILTER (WHERE plan = 'premium') as premium,\n  ROUND(AVG(lifetime_value), 2) as avg_ltv\nFROM users\nWHERE created_at >= '2024-01-01'\nGROUP BY 1 ORDER BY 1;",
        "WITH ranked AS (\n  SELECT p.*, ROW_NUMBER() OVER (PARTITION BY category_id ORDER BY sales DESC) as rank\n  FROM products p\n)\nSELECT * FROM ranked WHERE rank <= 3;",
        "DELETE FROM sessions WHERE last_active < NOW() - INTERVAL '30 days';\nDELETE FROM temp_uploads WHERE created_at < NOW() - INTERVAL '7 days';",
        "SELECT e.name, d.name as dept, e.salary,\n  AVG(e.salary) OVER (PARTITION BY d.name) as dept_avg\nFROM employees e\nJOIN departments d ON e.dept_id = d.id;",
        "ALTER TABLE users ADD COLUMN phone VARCHAR(20);\nALTER TABLE users ADD CONSTRAINT unique_email UNIQUE (email);\nCREATE INDEX idx_users_created ON users(created_at DESC);",
        "SELECT p.name, c.name as category,\n  COUNT(r.id) as review_count,\n  ROUND(AVG(r.rating), 1) as avg_rating\nFROM products p\nJOIN categories c ON p.category_id = c.id\nLEFT JOIN reviews r ON p.id = r.product_id\nGROUP BY p.id, p.name, c.name\nHAVING AVG(r.rating) < 3.0;",
        "EXPLAIN ANALYZE\nSELECT * FROM orders\nWHERE user_id = 42 AND status IN ('pending', 'processing')\nORDER BY created_at DESC LIMIT 10;",
        "INSERT INTO audit_log (user_id, action, table_name, record_id, old_data, new_data)\nVALUES (1, 'UPDATE', 'products', 42, '{\"price\": 29.99}', '{\"price\": 34.99}');",
    ]),
    (["contract", "legal", "compliance"], "Paste contract or legal text...", "⚖️ Legal Text", [
        "Section 5.2 - Limitation of Liability: The Provider shall not be liable for any indirect, incidental, consequential, or punitive damages arising from this Agreement.",
        "The Contractor agrees to a non-compete period of 24 months following termination, covering all territories where the Company operates.",
        "Force Majeure: Neither party shall be liable for failure to perform due to acts of God, war, terrorism, pandemic, or any cause beyond reasonable control.",
        "Intellectual Property: All work product created during the term shall be considered 'work for hire' and the sole property of the Client.",
        "Termination for Convenience: Either party may terminate this Agreement with 30 days written notice.",
        "Indemnification: The Vendor shall indemnify and hold harmless the Client from any third-party claims arising from negligence or breach.",
        "Data Processing Agreement: The Processor shall process personal data only on documented instructions from the Controller per GDPR Article 32.",
        "Auto-Renewal: This Agreement shall automatically renew for successive 12-month periods unless 90 days written notice is provided.",
        "Warranty: The Provider warrants the software will perform substantially per documentation for 12 months. Sole remedy: repair or replace.",
        "Governing Law: This Agreement shall be governed by the laws of the State of Delaware. Disputes resolved through binding arbitration.",
        "Confidentiality: Both parties agree to maintain strict confidentiality of proprietary information for 5 years after termination.",
    ]),
    (["resume", "interview", "job", "career"], "Paste resume or job description...", "💼 Career Content", [
        "Senior Full-Stack Developer | 5 years experience\n\nSkills: React, Node.js, Python, PostgreSQL, AWS, Docker\n\nExperience:\n- Led migration from monolith to microservices (40% latency reduction)\n- Built real-time analytics dashboard serving 10K daily users",
        "Job Description: DevOps Engineer\nRequirements: 3+ years with Kubernetes and Docker, CI/CD experience, AWS cert preferred\nSalary: $130K-$160K + equity",
        "Tell me about a time you dealt with a difficult stakeholder.\n\nThe VP of Sales wanted a feature shipped in 2 weeks that we estimated at 6 weeks. I organized a scope workshop to identify the MVP.",
        "Junior Developer | Recent Bootcamp Graduate\n\nProjects: E-commerce app (React, Node, MongoDB), Weather dashboard with API integration\nSeeking: Entry-level position, willing to relocate",
        "What's your biggest weakness?\n\nI tend to over-engineer solutions. I've learned to balance this by setting time limits for design phases.",
        "Data Scientist Resume:\n- PhD in Statistics, Stanford\n- 3 years at FAANG\n- Published 5 papers in NeurIPS/ICML\n- Built ML pipeline processing 2TB daily",
        "Why do you want to work here?\n\nI've been using your product for 2 years and noticed the recent pivot to AI. My background in NLP directly aligns with your roadmap.",
        "System Design Interview:\nDesign a URL shortener like bit.ly.\nRequirements: 100M URLs/day, 10:1 read/write ratio, custom aliases, analytics.",
        "Cover Letter:\nDear Hiring Manager,\nI'm excited to apply for the Product Manager role. With 4 years at a B2B SaaS company, I've shipped 3 major features that increased ARR by 40%.",
        "References:\n1. Jane Smith, CTO at TechCo - jane@techco.com\n2. Bob Johnson, Team Lead at StartupXYZ - bob@xyz.com\n3. Dr. Alice Wang, Professor at MIT - awang@mit.edu",
    ]),
    (["security", "vulnerability", "password", "hash", "encrypt"], "Paste code, config, or text to audit...", "🔒 Security Input", [
        'app.use(cors({ origin: "*" }));\nconst db = mysql.createConnection({ host: "prod-db", user: "root", password: "admin123" });',
        'const token = jwt.sign(payload, "mysecretkey123", { expiresIn: "30d" });\n// TODO: rotate secret key someday',
        'app.get("/users/:id", (req, res) => {\n  const query = `SELECT * FROM users WHERE id = ${req.params.id}`;\n  db.query(query, (err, r) => res.json(r));\n});',
        "AWS_ACCESS_KEY_ID=AKIAIOSFODNN7EXAMPLE\nAWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY\nDATABASE_URL=postgres://admin:pass123@db.example.com/prod",
        'eval(req.body.code);\n// Allow users to run custom scripts',
        'password_hash = md5(password)\ndb.execute("INSERT INTO users (email, password) VALUES (?, ?)", [email, password_hash])',
        '<form action="/login" method="POST">\n  <input type="password" name="password">\n  <!-- No CSRF token -->\n  <button>Login</button>\n</form>',
        'res.setHeader("Access-Control-Allow-Origin", "*");\nres.setHeader("X-Powered-By", "Express 4.18.2");\n// No rate limiting or helmet',
        'const upload = multer({ dest: "uploads/" });\napp.post("/upload", upload.single("file"), (req, res) => {\n  // No file type validation, no size limit\n  res.json({ path: req.file.path });\n});',
        'if (password === "admin" || password === storedPassword) {\n  req.session.isAdmin = true;\n  req.session.cookie.secure = false;\n}',
        'subprocess.call(f"ping {user_input}", shell=True)',
    ]),
    (["docker", "k8s", "kubernetes", "ci-pipeline", "deploy"], "Paste config (Dockerfile, YAML, CI)...", "🐳 DevOps Config", [
        'FROM node:18\nWORKDIR /app\nCOPY package*.json ./\nRUN npm install\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]',
        'FROM python:3.12-slim\nRUN pip install flask gunicorn\nCOPY . /app\nWORKDIR /app\nCMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:8000", "app:app"]',
        "apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: web-app\nspec:\n  replicas: 3\n  template:\n    spec:\n      containers:\n      - name: web\n        image: myapp:latest\n        resources:\n          limits:\n            memory: 512Mi",
        "version: '3.8'\nservices:\n  web:\n    build: .\n    ports: ['3000:3000']\n    depends_on: [db, redis]\n  db:\n    image: postgres:16\n  redis:\n    image: redis:7-alpine",
        "name: CI\non: [push, pull_request]\njobs:\n  test:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - run: npm ci\n      - run: npm test",
        "FROM node:18 AS builder\nWORKDIR /app\nCOPY . .\nRUN npm ci && npm run build\n\nFROM nginx:alpine\nCOPY --from=builder /app/dist /usr/share/nginx/html",
        "apiVersion: v1\nkind: Service\nmetadata:\n  name: web-service\nspec:\n  type: LoadBalancer\n  ports:\n  - port: 80\n    targetPort: 8080",
        'resource "aws_instance" "web" {\n  ami           = "ami-0c55b159cbfafe1f0"\n  instance_type = "t3.medium"\n  tags = { Name = "production-web" }\n}',
        "FROM ubuntu:22.04\nRUN apt-get update && apt-get install -y curl wget git nodejs\nCOPY . /app\nWORKDIR /app\nRUN npm install\nCMD npm start",
        "apiVersion: autoscaling/v2\nkind: HorizontalPodAutoscaler\nspec:\n  minReplicas: 2\n  maxReplicas: 10\n  metrics:\n  - type: Resource\n    resource:\n      name: cpu\n      target:\n        averageUtilization: 70",
    ]),
    (["git ", "changelog", "commit", "diff", "version bump"], "Paste commit messages, diff, or branch info...", "🗂️ Git Content", [
        "feat: add user authentication with JWT tokens\nfix: resolve memory leak in WebSocket handler\nrefactor: extract payment logic into service layer\nfeat: add rate limiting middleware (100 req/min)",
        "feat(auth): implement OAuth2 with Google and GitHub\nfeat(auth): add magic link login\nfix(auth): token refresh race condition\ntest(auth): add integration tests",
        "BREAKING CHANGE: rename /api/users to /api/v2/users\n- Old endpoint returns 301\n- New response includes pagination\n- Rate limit changed from 100 to 60/min",
        "v2.1.0 Release Notes:\n- Added dark mode support\n- Fixed crash on iOS 16 rotation\n- Improved load time by 35%\n- New: CSV export\n- Deprecated: XML export",
        "fix: prevent XSS in user bio (#1234)\nfix: sanitize file uploads (#1235)\nfix: add CSRF token to forms (#1236)\nsec: upgrade lodash for prototype pollution",
        "chore: upgrade to React 19\nchore: migrate Jest to Vitest\nchore: replace Moment.js with date-fns\nchore: bump Node to 20 LTS",
        "Merge branch 'feature/payments' into main\n\nAdds Stripe integration:\n- Checkout flow with 3D Secure\n- Subscription management\n- Webhook handlers\n\n47 files changed, 2,341 insertions(+)",
        "revert: undo migration to new ORM (#892)\n\nReason: 3x performance regression on complex joins\nReverting until fixes are ready",
        "feat: real-time notifications\nfeat: notification preferences UI\nfeat: push notifications (FCM)\nfix: notification sound on iOS\nperf: batch notification queries",
        "git log --oneline:\na1b2c3d fix: null pointer in user service\nd4e5f6g feat: add search filters\nh7i8j9k refactor: simplify middleware\nl0m1n2o test: coverage to 85%\np3q4r5s ci: add staging deploy",
    ]),
    (["cors", "rate-limit", "uptime", "url", "link check", "endpoint"], "Enter a URL or API endpoint...", "🔗 Enter URL", [
        "https://api.github.com/repos/vercel/next.js",
        "https://jsonplaceholder.typicode.com/posts",
        "https://httpbin.org/status/200",
        "https://api.stripe.com/v1/charges",
        "https://api.openai.com/v1/models",
        "https://registry.npmjs.org/react",
        "https://api.spotify.com/v1/search?q=jazz&type=track",
        "https://pokeapi.co/api/v2/pokemon/pikachu",
        "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd",
        "https://catfact.ninja/fact",
        "https://www.googleapis.com/books/v1/volumes?q=python",
    ]),
    (["blog", "seo", "article", "copy editor", "content writ", "post writer"], "Enter a topic or paste your draft...", "✍️ Topic or Draft", [
        "Write a blog post about: How AI coding assistants are changing software development in 2025.",
        "Draft: 5 Common Mistakes in REST API Design\n1. Not using proper HTTP status codes\n2. Inconsistent naming\n3. Missing pagination\n4. No versioning\n[Need to expand each with examples]",
        "Topic: Why TypeScript is replacing JavaScript in enterprise apps\nAudience: Senior developers\nTone: Persuasive but balanced\nLength: 1500 words",
        "Write an SEO article targeting 'best project management tools 2025'\nKeywords: agile tools, Jira alternatives\nWord count: 2000",
        "Edit this intro: So like, in todays world of technology, there is alot of tools that developers use. But which ones are the best? In this article we will talk about 10 tools that every developer should definately know about.",
        "Write a technical tutorial: Building a real-time chat app with WebSockets\nStack: Node.js, Socket.io, React\nInclude code snippets and deployment tips",
        "Topic: The Rise of Edge Computing for Web Developers\nExamples: Cloudflare Workers, Vercel Edge Functions, Deno Deploy",
        "Listicle: 7 VS Code Extensions That Will 10x Your Productivity\nStyle: Casual, engaging\nInclude hotkey tips",
        "Opinion piece: Why every startup should open-source their core library\nPros: community trust, free marketing\nCons: competitors, support burden",
        "Case study: How we reduced our AWS bill from $50K to $12K/month\nSections: Problem, What we tried, What worked, Results",
        "Comparison post: Next.js vs Remix vs Astro - Which framework in 2025?",
    ]),
    (["csv", "json", "log analyz", "log pars", "data analys", "parse"], "Paste your data (CSV, JSON, logs)...", "📊 Paste Data", [
        "name,age,city,score\nAlice,28,New York,92\nBob,35,London,87\nCharlie,22,Tokyo,95\nDiana,31,Paris,78\nEve,27,Berlin,91",
        '{"users": [{"id": 1, "name": "Alice", "active": true}, {"id": 2, "name": "Bob", "active": false}, {"id": 3, "name": "Charlie", "active": true}]}',
        "2024-01-15 14:23:01 ERROR [api-gateway] Request timeout after 30s\n2024-01-15 14:23:02 WARN [db-pool] Pool at 95% capacity (19/20)\n2024-01-15 14:23:05 ERROR [api-gateway] 503 Service Unavailable\n2024-01-15 14:23:08 INFO [auto-scaler] Scaling up: 3 -> 5 instances",
        "date,product,quantity,price,region\n2024-01-01,Widget A,150,29.99,North\n2024-01-01,Widget B,89,49.99,South\n2024-01-02,Widget A,200,29.99,East\n2024-01-02,Widget C,45,99.99,West",
        '[{"timestamp": "2024-01-15T10:00:00Z", "event": "page_view", "page": "/home"},\n {"timestamp": "2024-01-15T10:00:05Z", "event": "click", "element": "signup_btn"},\n {"timestamp": "2024-01-15T10:00:30Z", "event": "form_submit", "form": "registration"}]',
        "month,revenue,expenses,profit,headcount\n2024-01,120000,95000,25000,12\n2024-02,135000,98000,37000,13\n2024-03,128000,102000,26000,14\n2024-04,155000,105000,50000,15",
        '192.168.1.1 - - [15/Jan/2024:10:00:01] "GET /index.html HTTP/1.1" 200 4523\n192.168.1.2 - - [15/Jan/2024:10:00:02] "POST /api/login HTTP/1.1" 401 89\n192.168.1.2 - - [15/Jan/2024:10:00:03] "POST /api/login HTTP/1.1" 401 89',
        "student_id,math,science,english,history,grade\nS001,95,88,72,80,A\nS002,65,70,90,85,B\nS003,78,92,68,75,B\nS004,45,55,60,50,D",
        '{"server": "web-01", "cpu_usage": 78.5, "memory_mb": 3200, "disk_pct": 65, "requests_per_sec": 1250, "error_rate": 0.02}',
        "category,jan,feb,mar,apr,may\nElectronics,45000,52000,48000,61000,55000\nClothing,32000,28000,35000,40000,38000\nFood,18000,19000,20000,19500,21000",
        "ip_address,country,requests,blocked\n203.0.113.1,CN,15000,true\n198.51.100.2,US,8500,false\n192.0.2.3,RU,12000,true",
    ]),
    (["regex", "pattern", "match", "validator"], "Enter text or pattern to test...", "🔍 Text or Pattern", [
        "Pattern: ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$\n\nTest:\nuser@example.com\ninvalid-email@\nhello.world@company.co.uk",
        "Pattern: ^(?=.*[A-Z])(?=.*[0-9])(?=.*[!@#$%]).{8,}$\n\nTest: Password1! / weak / Strong@Pass99",
        "Pattern: \\b\\d{3}[-.]?\\d{3}[-.]?\\d{4}\\b\n\nTest: 555-123-4567 / 555.123.4567 / 5551234567",
        "Pattern: ^(https?://)?[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}(/\\S*)?$\n\nTest:\nhttps://example.com\nnot-a-url\nexample.com/path",
        "Pattern: ^\\d{4}-(0[1-9]|1[0-2])-(0[1-9]|[12]\\d|3[01])$\n\nTest: 2024-01-15 / 2024-13-01 / 2024-02-30",
        "Extract all hex color codes from:\n.btn { background: #FF6B6B; border: 1px solid #e55; }\nbody { color: #333; }",
        "Pattern: ^[A-Z]{2}\\d{6}[A-Z]$\n\nTest passport numbers:\nAB123456C / ab123456c / ABC12345D",
        "Find all IP addresses in:\nServer 192.168.1.1 responded in 23ms\nProxy at 172.16.0.1:8080 is down\nExternal: 8.8.8.8",
        "Pattern to match JSON keys:\n{\"firstName\": \"John\", \"lastName\": \"Doe\", \"age\": 30}",
        "Replace dates MM/DD/YYYY to YYYY-MM-DD:\n12/25/2024 / 01/01/2025 / 06/15/2024",
    ]),
    (["markdown", "html-to", "convert", "format"], "Paste content to convert...", "🔄 Content to Convert", [
        '<div class="container">\n  <h1>Welcome</h1>\n  <p>A <strong>sample</strong> page with <a href="https://example.com">a link</a>.</p>\n  <ul><li>Item 1</li><li>Item 2</li></ul>\n</div>',
        "# API Documentation\n\n## GET /users\nReturns a list of users.\n\n| Param | Type | Required |\n|-------|------|----------|\n| page  | int  | No       |",
        '<table>\n  <tr><th>Name</th><th>Role</th></tr>\n  <tr><td>Alice</td><td>Engineer</td></tr>\n  <tr><td>Bob</td><td>Designer</td></tr>\n</table>',
        "Convert to HTML:\n\n**Status Report**\n- [x] Backend complete\n- [ ] Frontend integration\n- [ ] Testing\n\n> Deadline: March 15th",
        '<nav class="sidebar">\n  <a href="/" class="active">Home</a>\n  <a href="/about">About</a>\n  <a href="/contact">Contact</a>\n</nav>',
        "---\ntitle: My Blog Post\ndate: 2024-01-15\ntags: [python, tutorial]\n---\n\n# Getting Started with FastAPI\n\nFastAPI is a modern Python framework...",
        '<form>\n  <label for="name">Name:</label>\n  <input type="text" id="name" required>\n  <button type="submit">Submit</button>\n</form>',
        "Convert RST to Markdown:\n\nTitle\n=====\n\n.. code-block:: python\n\n   def hello():\n       print('world')",
        "Plain text to Markdown:\nMeeting Notes - Jan 15\nAttendees: Alice, Bob\nAction Items:\n- Alice: Draft proposal by Friday\n- Bob: Schedule interviews",
        '<article>\n  <h2>Breaking: New Framework Released</h2>\n  <p class="meta">By Jane Doe | Jan 15, 2024</p>\n  <p>A revolutionary framework was released today...</p>\n</article>',
    ]),
    (["translate", "i18n", "localize"], "Paste text to translate...", "🌐 Text to Translate", [
        "Welcome to our platform! Your account has been created successfully. Please verify your email to get started.",
        "Error: Your session has expired. Please log in again to continue.",
        "Your order #12345 has been shipped and will arrive in 3-5 business days.",
        "Terms of Service: By using this application, you agree to our privacy policy. You must be at least 18 years old.",
        "Congratulations! You've completed all challenges. Your certificate is ready for download.",
        "Settings > Notifications\n- Product updates\n- Security alerts\n- Marketing newsletters\n- Weekly digest",
        "404 - Page Not Found. The page you're looking for doesn't exist or has been moved.",
        "Please enter a valid credit card number. We accept Visa, Mastercard, and American Express.",
        "Your free trial ends in 3 days. Upgrade to Pro to keep all your data.",
        "We value your feedback! Rate your experience from 1-5 stars.",
        "Privacy Notice: We collect cookies to improve your experience. Manage preferences in Settings.",
    ]),
    (["color", "css", "svg", "figma", "accessibility", "ascii art"], "Paste CSS, HTML, or describe design...", "🎨 Design Input", [
        ".card {\n  background: #1a1a2e;\n  color: #eee;\n  border-radius: 12px;\n  padding: 24px;\n  box-shadow: 0 4px 20px rgba(0,0,0,0.3);\n}",
        "Create a color palette for a finance app. Should feel: trustworthy, modern, professional.",
        ".btn {\n  background: linear-gradient(135deg, #667eea, #764ba2);\n  color: white;\n  transition: transform 0.2s;\n}\n.btn:hover { transform: translateY(-2px); }",
        'Check WCAG 2.1 AA:\n<button style="background: #aaa; color: #ccc; font-size: 10px;">Submit</button>\n<img src="chart.png">\n<div onclick="navigate()">Click here</div>',
        "Convert HEX to HSL:\n#FF6B6B / #4ECDC4 / #2C3E50 / #E74C3C / #3498DB",
        "Design tokens for a dark theme:\n- 3 background depths\n- 4 text hierarchy levels\n- Accent colors: primary, success, error\n- Shadows",
        "Generate ASCII art for: a rocket ship launching",
        '<svg viewBox="0 0 100 100">\n  <circle cx="50" cy="50" r="40" fill="#FF6B6B"/>\n  <text x="50" y="55" text-anchor="middle">80%</text>\n</svg>\nMake this a progress ring with animation.',
        "Spacing check:\n.container { padding: 13px; }\n.card { margin: 7px 15px; }\n.title { margin-bottom: 11px; }\n\nShould these follow 4px or 8px grid?",
        "Generate CSS animation: fade in from bottom, 0.6s ease-out, stagger children by 100ms, respect prefers-reduced-motion",
    ]),
    (["recipe", "meal", "food", "nutrition"], "Enter ingredients or dietary preferences...", "🍽️ Food / Ingredients", [
        "I have: chicken breast, broccoli, garlic, soy sauce, rice, sesame oil, ginger. Healthy dinner recipe?",
        "Ingredients: canned chickpeas, spinach, onion, tomato paste, cumin. Vegan dinner in 20 min.",
        "Meal plan for the week. Budget: $50. Family of 3. One person lactose intolerant.",
        "Meal prep 5 lunches. High protein (30g+), under 500 cal each. No seafood.",
        "What can I make with: eggs, flour, butter, sugar, vanilla, baking powder? Dinner party dessert.",
        "Convert recipe to metric: 2 cups flour, 1/2 cup butter, 3/4 cup sugar, 350°F oven, 1 tbsp vanilla",
        "Post-workout smoothie: needs 30g protein, banana, recovery ingredients. No dairy.",
        "Keto meal with: ground beef, cheese, avocado, lettuce, tomatoes, sour cream?",
        "Rate nutritionally: 6oz grilled salmon + 1 cup brown rice + steamed asparagus + olive oil dressing",
        "Substitutes: eggs (vegan cake), heavy cream (lactose free), soy sauce (gluten free), white sugar (healthier)",
        "Calculate macros: 200g chicken breast + 150g sweet potato + 100g broccoli + 1 tbsp olive oil",
    ]),
    (["habit", "mood", "journal", "wellness"], "Describe your goal or current situation...", "🧘 Your Situation", [
        "I want to build a morning routine. Currently wake at 8am, check phone 30 min, rush to work.",
        "Procrastinating on a big project for 2 weeks. I know what to do but can't start. Deadline in 5 days.",
        "Mood today: anxious. Kept thinking about tomorrow's presentation. Couldn't focus. Skipped lunch.",
        "Want to read more books. Last year I read 2. Goal: 24 this year. I have 30 min before bed.",
        "Started exercising 3 weeks ago. Week 1: 4 times. Week 2: 2 times. Week 3: 0 times. How to stay consistent?",
        "Daily entry: Woke up tired but forced gym. Work was stressful, conflict with coworker. Evening: cooked dinner, called mom.",
        "Want to reduce screen time. Currently 7 hours/day. Most used: TikTok (2h), Instagram (1.5h), YouTube (1h).",
        "Gratitude journal:\n1. Sunny weather today\n2. Great conversation with old friend\n3. Fixed a difficult bug at work\nWhat else to reflect on?",
        "Sleep terribly. Bed at midnight, phone until 1am, wake 6:30am. Exhausted by 2pm daily.",
        "Want to learn Spanish. Available: 15 min/day. Budget: $0. Current level: hola and counting to 10.",
    ]),
    (["gift", "recommend"], "Describe the person and occasion...", "🎁 Context", [
        "Friend turning 30. Loves hiking, photography, cooking. Budget: $50-100.",
        "Anniversary gift for wife. Together 10 years. Into yoga, reading, interior design. Budget: $150-200.",
        "Graduation gift for nephew (18). Going to CS in college. Budget: $30-50.",
        "Secret Santa at work. Person likes coffee, guitar, has a dog. Budget: $25 max.",
        "Thank you gift for kids' teacher. Taught them 2 years. Thoughtful, not just gift card. Budget: $40.",
        "Housewarming for couple. First home. Minimalist design taste. Budget: $50-75.",
        "Dad retiring after 35 years. Loves golf, whiskey, history docs. Budget: $100-200.",
        "Baby shower. First-time parents, having a girl. Already have basics. Budget: $50-80.",
        "Coworker leaving company. Worked together 3 years. Something memorable. Budget: $30-50.",
        "Valentine's for boyfriend. Gamer, loves sci-fi, learning to cook. Budget: $50-100.",
    ]),
    (["test gen", "unit test", "spec gen", "mock"], "Paste code to generate tests for...", "🧪 Code to Test", [
        "def calculate_discount(price, quantity, is_member):\n    if quantity >= 10:\n        discount = 0.15\n    elif quantity >= 5:\n        discount = 0.10\n    else:\n        discount = 0\n    if is_member:\n        discount += 0.05\n    return round(price * quantity * (1 - discount), 2)",
        "function validateEmail(email) {\n  if (!email) return { valid: false, error: 'Email required' };\n  const re = /^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$/;\n  if (!re.test(email)) return { valid: false, error: 'Invalid' };\n  return { valid: true };\n}",
        "class ShoppingCart:\n    def __init__(self):\n        self.items = []\n    def add_item(self, name, price, qty=1):\n        self.items.append({'name': name, 'price': price, 'qty': qty})\n    def remove_item(self, name):\n        self.items = [i for i in self.items if i['name'] != name]\n    def total(self):\n        return sum(i['price'] * i['qty'] for i in self.items)",
        "async function fetchUserData(userId) {\n  const response = await fetch(`/api/users/${userId}`);\n  if (!response.ok) throw new Error(`HTTP ${response.status}`);\n  return await response.json();\n}",
        "def parse_csv_line(line, delimiter=','):\n    fields, current, in_quotes = [], '', False\n    for char in line:\n        if char == '\"': in_quotes = not in_quotes\n        elif char == delimiter and not in_quotes:\n            fields.append(current.strip()); current = ''\n        else: current += char\n    fields.append(current.strip())\n    return fields",
        "function debounce(fn, delay) {\n  let timer = null;\n  return function(...args) {\n    clearTimeout(timer);\n    timer = setTimeout(() => fn.apply(this, args), delay);\n  };\n}",
        "class PasswordValidator:\n    def __init__(self, min_length=8):\n        self.min_length = min_length\n    def validate(self, password):\n        errors = []\n        if len(password) < self.min_length: errors.append('too_short')\n        if not any(c.isupper() for c in password): errors.append('no_uppercase')\n        if not any(c.isdigit() for c in password): errors.append('no_digit')\n        return len(errors) == 0, errors",
        "function formatCurrency(amount, currency = 'USD') {\n  return new Intl.NumberFormat('en-US', {\n    style: 'currency', currency,\n    minimumFractionDigits: 2\n  }).format(amount);\n}",
        "def merge_sorted(list1, list2):\n    result, i, j = [], 0, 0\n    while i < len(list1) and j < len(list2):\n        if list1[i] <= list2[j]: result.append(list1[i]); i += 1\n        else: result.append(list2[j]); j += 1\n    result.extend(list1[i:]); result.extend(list2[j:])\n    return result",
        "function retry(fn, maxRetries = 3, delay = 1000) {\n  return async (...args) => {\n    for (let i = 0; i <= maxRetries; i++) {\n      try { return await fn(...args); }\n      catch (err) {\n        if (i === maxRetries) throw err;\n        await new Promise(r => setTimeout(r, delay * (i + 1)));\n      }\n    }\n  };\n}",
    ]),
    (["readme", "doc writer", "documentation"], "Paste code or describe what to document...", "📖 Code / Description", [
        "class RateLimiter:\n    def __init__(self, max_requests, window_seconds):\n        self.max_requests = max_requests\n        self.window = window_seconds\n        self.requests = {}\n    def is_allowed(self, client_id):\n        now = time.time()\n        self._cleanup(client_id, now)\n        if len(self.requests.get(client_id, [])) >= self.max_requests:\n            return False\n        self.requests.setdefault(client_id, []).append(now)\n        return True",
        "Document this CLI:\nUsage: imgopt [options] <input>\n-o, --output <dir>    Output directory\n-q, --quality <n>     Quality 1-100 (default: 80)\n-f, --format          webp|avif|png (default: webp)\n-r, --resize <WxH>    Resize dimensions",
        "Write API docs:\nPOST /api/auth/login\nBody: { email, password }\nReturns: { token, user, expiresAt }\nErrors: 401, 429, 422",
        "Document React component:\nfunction DataTable({ data, columns, sortable, onRowClick, loading, emptyMessage, pageSize })\n// Sortable, paginated table with skeleton loading",
        "Generate CONTRIBUTING.md:\nLanguage: Python, Package: Poetry, Tests: pytest, Lint: ruff, CI: GitHub Actions, License: MIT",
        "Write changelog:\n- Added WebSocket support\n- Fixed memory leak on large files\n- Deprecated /v1/legacy endpoint\n- 40% query performance improvement\n- Breaking: userId → user_id",
        "Document schema:\nusers: id (UUID), email, name, plan\nteams: id, name, owner_id (FK users)\nteam_members: team_id, user_id, role\nprojects: id, team_id, name, status",
        "Installation docs for Node.js package:\nRequires Node 18+, peers: React 18+, TypeScript 5+\nEnv vars: API_KEY, DATABASE_URL\nSupports ESM and CommonJS",
        "Document error pattern:\nclass AppError extends Error {\n  constructor(message, statusCode, code) {\n    super(message);\n    this.statusCode = statusCode;\n    this.isOperational = true;\n  }\n}",
        "Migration guide v2 → v3:\n- Config: JSON → YAML\n- auth() now returns Promise\n- Removed: legacyMode\n- Renamed: onError → onFailure\n- New required: apiVersion in config",
    ]),
    (["code", "review", "bug", "lint", "style", "refactor", "dead code", "complexity", "api"], "Paste your code here...", "📝 Paste Code", [
        "def process_data(data):\n    result = []\n    for i in range(len(data)):\n        if data[i] != None:\n            temp = data[i]\n            if type(temp) == str:\n                temp = temp.strip()\n                if temp != '':\n                    result.append(temp)\n            elif type(temp) == int:\n                if temp > 0:\n                    result.append(temp)\n    return result",
        "function fetchUser(id) {\n  return fetch('/api/users/' + id)\n    .then(function(r) {\n      if (r.status == 200) return r.json()\n      else return null\n    })\n    .catch(function(err) { console.log(err) })\n}",
        "class UserService:\n    def get_user(self, id):\n        user = db.query(f'SELECT * FROM users WHERE id = {id}')\n        return user if user else None\n    def update_user(self, id, data):\n        db.query(f\"UPDATE users SET name = '{data['name']}' WHERE id = {id}\")",
        "const processOrders = (orders) => {\n  let total = 0, count = 0, items = [];\n  for (let i = 0; i < orders.length; i++) {\n    if (orders[i].status === 'completed') {\n      total += orders[i].amount;\n      count++;\n      for (let j = 0; j < orders[i].items.length; j++)\n        items.push(orders[i].items[j]);\n    }\n  }\n  return { total, count, items };\n};",
        "import os, sys, json, re, time\ndef analyze(path):\n    f = open(path, 'r')\n    data = f.read()\n    f.close()\n    lines = data.split('\\n')\n    result = []\n    for line in lines:\n        if line != '' and line != None:\n            result.append(line)\n    return result",
        "app.get('/api/admin/users', (req, res) => {\n  // No auth check\n  db.query('SELECT * FROM users', (err, r) => {\n    if (err) res.send('error')\n    res.json(r)\n  })\n})\napp.post('/api/admin/delete', (req, res) => {\n  db.query('DELETE FROM users WHERE id = ' + req.body.id)\n  res.send('ok')\n})",
        "def fibonacci(n):\n    if n == 0: return 0\n    if n == 1: return 1\n    if n == 2: return 1\n    if n == 3: return 2\n    if n == 4: return 3\n    if n == 5: return 5\n    return fibonacci(n-1) + fibonacci(n-2)",
        "class Config {\n  constructor() {\n    this.db_host = process.env.DB_HOST || 'localhost';\n    this.db_pass = process.env.DB_PASS || 'password123';\n    this.secret = process.env.JWT_SECRET;\n    this.debug = true;\n  }\n}",
        "async function saveUser(user) {\n  try { return await db.users.insert(user); }\n  catch (e) {\n    try { return await db.users.update(user); }\n    catch (e2) {\n      try { await db.users.upsert(user); }\n      catch (e3) { console.log('gave up'); return null; }\n    }\n  }\n}",
        "def check_password(password):\n    if len(password) < 8: return False\n    has_upper = has_lower = has_digit = has_special = False\n    for char in password:\n        if char.isupper(): has_upper = True\n        if char.islower(): has_lower = True\n        if char.isdigit(): has_digit = True\n        if char in '!@#$%^&*': has_special = True\n    if has_upper and has_lower and has_digit and has_special:\n        return True\n    else:\n        return False",
        "function sortUsers(users, sortBy, sortOrder) {\n  if (sortBy === 'name') {\n    if (sortOrder === 'asc') users.sort((a, b) => a.name > b.name ? 1 : -1);\n    else users.sort((a, b) => a.name < b.name ? 1 : -1);\n  } else if (sortBy === 'age') {\n    if (sortOrder === 'asc') users.sort((a, b) => a.age - b.age);\n    else users.sort((a, b) => b.age - a.age);\n  }\n  return users;\n}",
    ]),
]

DEFAULT_EXAMPLES = [
    "Analyze: Our web app has 1,200 DAU with 4.5 min avg session. Bounce rate 45%, conversion 2.3%. Suggest improvements.",
    "Compare:\nA) Monolithic architecture, single database\nB) Microservices, separate databases\nContext: Team of 4, launching MVP in 3 months.",
    "Summarize:\n- Revenue +15% QoQ\n- Churn decreased 8% to 5%\n- NPS improved 32 to 48\n- Support tickets -30%\n- Two new enterprise clients",
    "Help brainstorm: CI pipeline takes 45 minutes. Developers pushing code less frequently. How to speed it up?",
    "Review project plan:\nWeek 1-2: Design\nWeek 3-4: Backend\nWeek 5-6: Frontend\nWeek 7: Testing\nWeek 8: Launch\nTeam: 2 full-stack devs + 1 designer",
    "Explain tradeoffs: SSR vs SSG vs CSR vs ISR for an e-commerce site with 10K products.",
    "Troubleshoot: Node.js API starts slow (2s) after deploy, improves to 200ms after ~100 requests. Memory stable.",
    "Decision matrix for choosing a database:\nOptions: PostgreSQL, MongoDB, DynamoDB, Supabase\nCriteria: Cost, scalability, DX, ecosystem",
    "Analyze user feedback:\n- 'App is great but I lose progress when switching tabs'\n- 'Love dark mode but text is too small'\n- 'Can you add PDF export?'\n- 'Search never finds what I'm looking for'",
    "Ideas for improving developer onboarding at a company with 50+ microservices, 12 languages, and docs scattered across Notion, Confluence, and READMEs.",
]


def get_agent_hint(agent):
    """Return (placeholder, label, examples_list) based on agent name keywords."""
    name = agent.get("name", "").lower()
    text = name

    for keywords, placeholder, label, examples in HINTS:
        if any(kw in text for kw in keywords):
            return placeholder, label, examples

    return "Describe what you need or paste your text...", "📝 Your Input", DEFAULT_EXAMPLES
