import os
import sys
import argparse
from typing import List, Dict, Any

# Ensure we can import tools
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from tools.audit import run_npm_audit, extract_vulnerabilities
from tools.patcher import get_installed_version, update_package, update_lockfile
from tools.tester import run_tests
from tools.git_utils import create_branch, commit_changes, push_changes, create_pr, get_repo
from tools.notifier import notify_team

from rich.console import Console
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.table import Table
from rich.panel import Panel

# Optional: LangChain for PR description
try:
    from langchain.llms import OpenAI
    from langchain.prompts import PromptTemplate
    HAS_LANGCHAIN = True
except ImportError:  # pragma: no cover
    HAS_LANGCHAIN = False  # pragma: no cover

console = Console()

def generate_pr_description(pkg_name: str, vulns: List[Dict[str, Any]], old_version: str, new_version: str) -> str:
    """Generates a PR description using OpenAI if available, otherwise a template."""
    vuln_summary = "\n".join([f"- {v['severity'].upper()}: {v.get('title', 'Vulnerability')}" for v in vulns])

    if HAS_LANGCHAIN and os.getenv("OPENAI_API_KEY"):
        try:  # pragma: no cover
            llm = OpenAI(temperature=0.7)  # pragma: no cover
            prompt = PromptTemplate(  # pragma: no cover
                input_variables=["package", "old_version", "new_version", "vuln_summary"],
                template="""
                Write a professional GitHub Pull Request description for a security patch.

                Package: {package}
                Update: {old_version} -> {new_version}
                Vulnerabilities Fixed:
                {vuln_summary}

                The PR should explain why this update is necessary and what it fixes.
                """
            )
            return llm.invoke(prompt.format(  # pragma: no cover
                package=pkg_name,
                old_version=old_version,
                new_version=new_version,
                vuln_summary=vuln_summary
            ))
        except Exception as e:  # pragma: no cover
            console.print(f"[yellow]Warning: Failed to generate PR description with AI: {e}[/yellow]")  # pragma: no cover

    return f"""
    # Security Patch: {pkg_name}

    Updates `{pkg_name}` from {old_version} to {new_version} to fix security vulnerabilities.

    ## Vulnerabilities Fixed
    {vuln_summary}

    Auto-generated by VulnAutoPatcher.
    """

def main():
    parser = argparse.ArgumentParser(description="VulnAutoPatcher: Automated security patching agent.")  # pragma: no cover
    parser.add_argument("--path", type=str, default=".", help="Path to the project to patch")  # pragma: no cover
    parser.add_argument("--dry-run", action="store_true", help="Do not push or create PRs")  # pragma: no cover
    parser.add_argument("--base-branch", type=str, default="main", help="Base branch to branch off from")  # pragma: no cover
    args = parser.parse_args()  # pragma: no cover

    project_path = args.path  # pragma: no cover
    base_branch = args.base_branch  # pragma: no cover

    console.print(Panel.fit("🛡️  VulnAutoPatcher Started", style="bold blue"))  # pragma: no cover

    # Check for dirty state
    try:  # pragma: no cover
        repo = get_repo(project_path)  # pragma: no cover
        if repo.is_dirty() or repo.untracked_files:  # pragma: no cover
            console.print("[red]Repo is dirty. Please commit or stash changes before running.[/red]")  # pragma: no cover
            return  # pragma: no cover
    except Exception as e:  # pragma: no cover
        console.print(f"[red]Error initializing git repo: {e}[/red]")  # pragma: no cover
        return  # pragma: no cover

    with Progress(  # pragma: no cover
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        console=console
    ) as progress:

        # Step 1: Audit
        task1 = progress.add_task("[cyan]Running npm audit...", total=None)  # pragma: no cover
        audit_report = run_npm_audit(project_path)  # pragma: no cover
        progress.update(task1, completed=True)  # pragma: no cover

        if "error" in audit_report:  # pragma: no cover
             console.print(f"[red]Error running audit: {audit_report['error']}[/red]")  # pragma: no cover
             return  # pragma: no cover

        vulnerabilities = extract_vulnerabilities(audit_report)  # pragma: no cover
        console.print(f"[green]Found {len(vulnerabilities)} vulnerabilities.[/green]")  # pragma: no cover

        if not vulnerabilities:  # pragma: no cover
            return  # pragma: no cover

        # Group vulnerabilities by package
        vulns_by_pkg = {}  # pragma: no cover
        for vuln in vulnerabilities:  # pragma: no cover
            pkg = vuln["package"]  # pragma: no cover
            if pkg not in vulns_by_pkg:  # pragma: no cover
                vulns_by_pkg[pkg] = []  # pragma: no cover
            vulns_by_pkg[pkg].append(vuln)  # pragma: no cover

        # Display Vulnerabilities
        table = Table(title="Vulnerabilities Found")  # pragma: no cover
        table.add_column("Package", style="cyan")  # pragma: no cover
        table.add_column("Severity", style="magenta")  # pragma: no cover
        table.add_column("Current Version", style="yellow")  # pragma: no cover
        table.add_column("Fix Info", style="green")  # pragma: no cover

        for pkg, vulns in vulns_by_pkg.items():  # pragma: no cover
            current_ver = get_installed_version(pkg, project_path)  # pragma: no cover
            # Store current version in vulns
            for v in vulns:  # pragma: no cover
                v["current_version"] = current_ver  # pragma: no cover

            max_severity = max([v["severity"] for v in vulns], key=lambda x: ["low", "moderate", "high", "critical"].index(x) if x in ["low", "moderate", "high", "critical"] else 0)  # pragma: no cover

            # Use fix info from first vuln (usually consistent per package)
            fix_info = "Available" if any(v["fix_available"] for v in vulns) else "None"  # pragma: no cover
            if any(v.get("fix_version") for v in vulns):  # pragma: no cover
                fix_info = next(v["fix_version"] for v in vulns if v.get("fix_version"))  # pragma: no cover

            table.add_row(  # pragma: no cover
                pkg,
                max_severity,
                current_ver or "Unknown",
                fix_info
            )

        console.print(table)  # pragma: no cover

        # Step 2: Patch Loop
        for pkg, vulns in vulns_by_pkg.items():  # pragma: no cover
            # Check if any have fix available
            if not any(v["fix_available"] for v in vulns):  # pragma: no cover
                console.print(f"[yellow]Skipping {pkg}: No fix available.[/yellow]")  # pragma: no cover
                continue  # pragma: no cover

            current_ver = vulns[0].get("current_version")  # pragma: no cover
            if not current_ver:  # pragma: no cover
                 console.print(f"[yellow]Skipping {pkg}: Could not determine current version.[/yellow]")  # pragma: no cover
                 continue  # pragma: no cover

            console.print(f"\n[bold]Attempting to patch {pkg}...[/bold]")  # pragma: no cover

            # Ensure we are on base branch
            try:  # pragma: no cover
                console.print(f"Checking out {base_branch}...")  # pragma: no cover
                repo.heads[base_branch].checkout()  # pragma: no cover
                # We assume local base is up to date or user handled it.
                # Attempt to pull? Maybe risky if conflicts.
            except Exception as e:  # pragma: no cover
                console.print(f"[red]Failed to checkout {base_branch}: {e}[/red]")  # pragma: no cover
                continue  # pragma: no cover

            # Create Branch
            branch_name = f"fix/{pkg}-security-update"  # pragma: no cover
            if not create_branch(branch_name, project_path):  # pragma: no cover
                console.print(f"[red]Failed to create branch {branch_name}.[/red]")  # pragma: no cover
                continue  # pragma: no cover

            # Determine Target Version
            target_version = "latest"  # pragma: no cover
            # Prefer explicit fix version if available
            fix_ver = next((v.get("fix_version") for v in vulns if v.get("fix_version")), None)  # pragma: no cover
            if fix_ver:  # pragma: no cover
                target_version = fix_ver  # pragma: no cover

            task_patch = progress.add_task(f"[cyan]Updating {pkg} to {target_version}...", total=None)  # pragma: no cover
            success = update_package(pkg, target_version, project_path)  # pragma: no cover
            progress.update(task_patch, completed=True)  # pragma: no cover

            if not success:  # pragma: no cover
                console.print(f"[red]Failed to update {pkg}.[/red]")  # pragma: no cover
                # Revert changes
                repo.git.checkout(".")  # pragma: no cover
                # Switch back to base
                repo.heads[base_branch].checkout()  # pragma: no cover
                continue  # pragma: no cover

            # Update Lockfile
            update_lockfile(project_path)  # pragma: no cover

            # Run Tests
            task_test = progress.add_task(f"[cyan]Running tests for {pkg}...", total=None)  # pragma: no cover
            test_result = run_tests(project_path)  # pragma: no cover
            progress.update(task_test, completed=True)  # pragma: no cover

            if test_result["success"]:  # pragma: no cover
                console.print(f"[green]Tests passed for {pkg}![/green]")  # pragma: no cover

                if not args.dry_run:  # pragma: no cover
                    commit_msg = f"fix(deps): update {pkg} to fix security vulnerability"  # pragma: no cover
                    if commit_changes(commit_msg, project_path):  # pragma: no cover
                        console.print(f"[green]Changes committed.[/green]")  # pragma: no cover

                        push_changes(branch_name, "origin", project_path)  # pragma: no cover
                        console.print(f"[green]Branch pushed.[/green]")  # pragma: no cover

                        # Get new version (actual installed)
                        new_ver = get_installed_version(pkg, project_path) or target_version  # pragma: no cover

                        pr_body = generate_pr_description(pkg, vulns, current_ver, new_ver)  # pragma: no cover
                        pr_url = create_pr(  # pragma: no cover
                            title=commit_msg,
                            body=pr_body,
                            head_branch=branch_name,
                            base_branch=base_branch,
                            repo_path=project_path
                        )

                        if pr_url:  # pragma: no cover
                            notify_team(f"PR Created for {pkg}: {pr_url}", level="success")  # pragma: no cover
                        else:
                            notify_team(f"Failed to create PR for {pkg}", level="error")  # pragma: no cover
                    else:
                         console.print("[yellow]No changes to commit.[/yellow]")  # pragma: no cover
                else:
                    console.print("[blue]Dry run: Skipping commit/push/PR.[/blue]")  # pragma: no cover

                # Cleanup: checkout base for next package
                # (Ideally delete local branch too to keep clean)
                repo.heads[base_branch].checkout()  # pragma: no cover

            else:
                console.print(f"[red]Tests failed for {pkg}.[/red]")  # pragma: no cover
                notify_team(f"Auto-patch failed for {pkg}. Manual intervention required.", level="error")  # pragma: no cover

                # Revert changes
                repo.git.checkout(".")  # pragma: no cover
                # Checkout base
                repo.heads[base_branch].checkout()  # pragma: no cover

if __name__ == "__main__":
    main()  # pragma: no cover
