from typing import Dict, Any, List
from pathlib import Path

from .state import MonorepoConfig
from .generator import MonorepoGenerator
from .tools import make_directory, write_file_content

class MonorepoAgent:
    def __init__(self, config: MonorepoConfig):
        self.config = config
        self.generator = MonorepoGenerator()
        self.root_dir = Path(config.project_name)

    def _get_context(self) -> Dict[str, Any]:
        return self.config.model_dump()

    def run(self):
        """Main execution flow."""
        self._create_structure()
        self._generate_root_files()
        self._generate_shared_configs()
        if self.config.ci_provider:
            self._generate_ci_files()
        self._generate_apps()
        self._generate_packages()

    def _create_structure(self):
        make_directory(str(self.root_dir))
        make_directory(str(self.root_dir / "apps"))
        make_directory(str(self.root_dir / "packages"))
        if self.config.monorepo_tool == "nx":
            make_directory(str(self.root_dir / "tools"))

    def _generate_root_files(self):
        # Generate package.json
        package_json = self.generator.generate_package_json(
            self.config.project_name,
            self.config.package_manager,
            self.config.monorepo_tool
        )
        write_file_content(str(self.root_dir / "package.json"), package_json)

        # Generate turbo.json or nx.json
        if self.config.monorepo_tool == "turbo":
            turbo_json = """{
  "$schema": "https://turbo.build/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**", ".next/**"]
    },
    "lint": {},
    "dev": {
      "cache": false,
      "persistent": true
    }
  }
}"""
            write_file_content(str(self.root_dir / "turbo.json"), turbo_json)

        # Generate README
        readme = self.generator.generate_readme(
            self.config.project_name,
            "A modern monorepo setup generated by Monorepo Setup Agent."
        )
        write_file_content(str(self.root_dir / "README.md"), readme)

        # Generate Changeset Config
        if self.config.include_changesets:
            changeset_config = """{
  "$schema": "https://unpkg.com/@changesets/config/schema.json",
  "changelog": "@changesets/cli/changelog",
  "commit": false,
  "fixed": [],
  "linked": [],
  "access": "public",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}"""
            write_file_content(str(self.root_dir / ".changeset/config.json"), changeset_config)

    def _generate_shared_configs(self):
        # Generate tsconfig.json
        tsconfig = self.generator.generate_tsconfig(self.config.monorepo_tool)
        write_file_content(str(self.root_dir / "tsconfig.json"), tsconfig)

        # Example shared packages
        ui_pkg_dir = self.root_dir / "packages/ui"
        make_directory(str(ui_pkg_dir))
        write_file_content(str(ui_pkg_dir / "package.json"), f"""{{
  "name": "@repo/ui",
  "version": "0.0.0",
  "main": "./index.tsx",
  "types": "./index.tsx",
  "scripts": {{
    "lint": "eslint ."
  }}
}}""")
        write_file_content(str(ui_pkg_dir / "index.tsx"), "export * from './button';")
        write_file_content(str(ui_pkg_dir / "button.tsx"), "export const Button = () => <button>Click me</button>;")

    def _generate_ci_files(self):
        ci_dir = self.root_dir / ".github/workflows"
        make_directory(str(ci_dir))

        ci_content = self.generator.generate_ci_config(
            self.config.ci_provider,
            self.config.package_manager
        )
        write_file_content(str(ci_dir / "ci.yml"), ci_content)

    def _generate_apps(self):
        # Create a default web app
        web_app_dir = self.root_dir / "apps/web"
        make_directory(str(web_app_dir))
        write_file_content(str(web_app_dir / "package.json"), f"""{{
  "name": "web",
  "version": "0.0.0",
  "scripts": {{
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  }},
  "dependencies": {{
    "next": "latest",
    "react": "latest",
    "react-dom": "latest",
    "@repo/ui": "workspace:*"
  }}
}}""")

    def _generate_packages(self):
        # Ensure packages/ dir exists
        packages_dir = self.root_dir / "packages"
        make_directory(str(packages_dir))

        for pkg in self.config.packages:
            pkg_dir = packages_dir / pkg.name.replace("@repo/", "")
            make_directory(str(pkg_dir))

            # Generate package.json for the package
            pkg_json = f"""{{
  "name": "{pkg.name}",
  "version": "0.0.0",
  "main": "./index.ts",
  "types": "./index.ts",
  "scripts": {{
    "lint": "eslint ."
  }}
}}"""
            write_file_content(str(pkg_dir / "package.json"), pkg_json)
            write_file_content(str(pkg_dir / "index.ts"), "// Entry point")
