"""
MCP Server Builder Agent — scaffolds MCP server projects from descriptions.
Usage: python main.py <description>
"""
import argparse
import json
import os
import re
import sys


def run(user_input: str, api_key: str = "", model: str = "gpt-4o-mini") -> str:
    return "[MCP Server Builder] Describe your MCP server tools and I'll generate the project scaffold."


def parse_tool_description(desc: str) -> list:
    tools = []
    lines = desc.strip().splitlines()
    for line in lines:
        line = line.strip().lstrip("- ")
        if not line:
            continue
        name_match = re.match(r"^(\w+)[\s:—-]+(.+)", line)
        if name_match:
            tools.append({"name": name_match.group(1).lower().replace(" ", "_"),
                          "description": name_match.group(2).strip()})
        else:
            slug = re.sub(r"\W+", "_", line.lower()).strip("_")[:30]
            tools.append({"name": slug, "description": line})
    return tools or [{"name": "hello_world", "description": "A sample tool"}]


def generate_tool_schema(tool: dict) -> dict:
    return {
        "name": tool["name"],
        "description": tool["description"],
        "inputSchema": {
            "type": "object",
            "properties": {"input": {"type": "string", "description": "Input for the tool"}},
            "required": ["input"]
        }
    }


def generate_handler(tool: dict) -> str:
    return f'''async def handle_{tool["name"]}(arguments: dict) -> str:
    """Handler for {tool["name"]}: {tool["description"]}"""
    user_input = arguments.get("input", "")
    # TODO: Implement actual logic
    return f"[{tool["name"]}] Processed: {{user_input}}"
'''


def generate_server_code(tools: list, server_name: str = "my-mcp-server") -> str:
    handlers = "\n\n".join(generate_handler(t) for t in tools)
    tool_names = ", ".join(f'"{t["name"]}"' for t in tools)
    return f'''"""
MCP Server: {server_name}
Auto-generated by MCP Server Builder Agent
"""
import json
import sys

# Tool handlers
{handlers}

TOOLS = [{tool_names}]

def list_tools():
    return {json.dumps([generate_tool_schema(t) for t in tools], indent=2)}

def main():
    print(f"MCP Server '{server_name}' ready with {{len(TOOLS)}} tool(s)")
    for t in TOOLS:
        print(f"  - {{t}}")

if __name__ == "__main__":
    main()
'''


def generate_project(tools: list, server_name: str, output_dir: str = "") -> dict:
    files = {
        "server.py": generate_server_code(tools, server_name),
        "README.md": f"# {server_name}\n\nMCP server with {len(tools)} tool(s).\n\n## Tools\n" +
                     "\n".join(f"- **{t['name']}**: {t['description']}" for t in tools),
    }
    return files


def format_preview(tools: list, server_name: str) -> str:
    lines = [f"🔧 MCP Server: {server_name}", f"   Tools: {len(tools)}\n"]
    for t in tools:
        lines.append(f"   📌 {t['name']}: {t['description']}")
    lines.append("\n   Files to generate: server.py, README.md")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="MCP Server Builder Agent")
    parser.add_argument("description", nargs="?", help="Tool descriptions (one per line)")
    parser.add_argument("--name", default="my-mcp-server", help="Server name")
    args = parser.parse_args()
    if not args.description:
        print("MCP Server Builder Agent\nUsage: python main.py 'tool1: does X\\ntool2: does Y'")
        sys.exit(0)
    tools = parse_tool_description(args.description)
    print(format_preview(tools, args.name))


if __name__ == "__main__":  # pragma: no cover
    main()
