import markdown
from typing import Optional

class PolicyFormatter:
    """
    Formats generated privacy policies into different output formats (Markdown, HTML).
    """

    @staticmethod
    def to_markdown(policy_text: str) -> str:
        """Returns the policy text as Markdown (which it already is)."""
        return policy_text

    @staticmethod
    def to_html(policy_text: str, title: str = "Privacy Policy") -> str:
        """Converts Markdown policy text to a clean, styled HTML document."""
        html_content = markdown.markdown(policy_text)

        template = f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 2rem;
            color: #333;
            background-color: #f9f9f9;
        }}
        .container {{
            background: white;
            padding: 3rem;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
        }}
        h1, h2, h3 {{
            color: #2c3e50;
            margin-top: 1.5em;
        }}
        h1 {{
            border-bottom: 2px solid #eee;
            padding-bottom: 0.5rem;
        }}
        a {{
            color: #3498db;
            text-decoration: none;
        }}
        a:hover {{
            text-decoration: underline;
        }}
        footer {{
            margin-top: 3rem;
            text-align: center;
            font-size: 0.8rem;
            color: #7f8c8d;
        }}
    </style>
</head>
<body>
    <div class="container">
        {html_content}
    </div>
    <footer>
        Generated by Privacy Policy Generator Agent
    </footer>
</body>
</html>
"""
        return template
